Vagrant.require_version ">= 2.2.0"

Vagrant.configure(2) do |config|

  config.vm.box = "gbailey/amzn2" # https://github.com/gebailey/vagrant-boxes/tree/master/amzn2

  config.ssh.insert_key = false

  # Needed to avoid error with missing Ansible filters etc.
  config.vm.provision "shell", inline: "curl 'https://bootstrap.pypa.io/get-pip.py' -o 'get-pip.py' && python 'get-pip.py' && sudo pip install --upgrade Jinja2"

  config.vm.provision "ansible_local" do |ansible|
    ansible.verbose = true
    ansible.playbook = "ansible-role-cis-amazon-linux.yml"
    ansible.install_mode = "pip"
    ansible.version = "2.6.15"
    ansible.extra_vars = {
      in_vagrant: true
    }
  end

end
