Vagrant.require_version ">= 2.2.0"

Vagrant.configure(2) do |config|

  config.vm.box = "gbailey/amzn2" # https://github.com/gebailey/vagrant-boxes/tree/master/amzn2

  config.ssh.insert_key = false

  # In order to avoid error with missing Ansible filters, we install the latest Jinja2.
  # This in turn requires pip to be installed. While at it, we install Ansible ourselves.
  $script = <<-SCRIPT
  yum -y install python3 python3-devel python3-pip
  pip3 install --upgrade pip
  /usr/local/bin/pip3 install --upgrade Jinja2 ansible==2.6.15
  SCRIPT

  config.vm.provision "shell", inline: $script

  config.vm.provision "ansible_local" do |ansible|
    ansible.verbose = true
    ansible.install = false
    ansible.playbook = "ansible-role-cis-amazon-linux.yml"
    ansible.extra_vars = {
      in_vm: true
    }
  end

end
