# Standards: 0.11
---

# Preflight checks
- name: ansible_distribution
  debug:
    var: ansible_distribution

- name: ansible_distribution_version
  debug:
    var: ansible_distribution_version

- name: Preflight - Fail if host is not suitable for this benchmark
  fail:
    msg: "This benchmark is not suitable for the destination operating system"
  when: (ansible_distribution is not defined) or (ansible_distribution_version is not defined) or (ansible_distribution_version not in cis_target_os_versions) or (ansible_distribution != cis_target_os_distribution)
  tags: always

- name: Sanity check
  fail:
    msg: "One of the variables in_vm or in_container must be set for this role to have any effect!"
  when: in_container is not defined and in_vm is not defined
  tags: always

- name: Running in VM?
  debug:
    msg: "*** Running in a Virtual Machine ***"
  when: in_container is not defined
  tags: always

- name: Running in ansible-container?
  debug:
    msg: "*** Running in ansible-container ***"
  when: in_vm is not defined
  tags: always

- name: List Level-1 exclusions
  debug:
    var: cis_level_1_exclusions

- name: List Level-2 exclusions
  debug:
    var: cis_level_2_exclusions
