# Standards: 1.0.0
---

# 1.1.12 Ensure separate partition exists for /var/log/audit (Scored)

- name: 1.1.12 - Ensure separate partition exists for /var/log/audit (Scored)
  mount:
    name: "{{ item.mountpoint }}"
    state: present
    fstype: "{{item.fstype}}"
    src: "{{item.device}}"
  with_items:
    - mountpoint: "{{cis_partition_mnt_val_log_audit}}"
      device: "{{cis_partition_dev_val_log_audit}}"
      fstype: "{{cis_partition_fs_val_log_audit}}"
  tags:
    - level-2
    - section-1
    - section-1.1
    - section-1.1.12
    - "1.1.12"
    - scored
