# Standards: 1.0.0
---

# 1.6.1.4 Ensure SETroubleshoot is not installed (Scored)

- name: 1.6.1.4 - Ensure SETroubleshoot is not installed (Scored)
  yum:
    name: setroubleshoot
    state: removed
  tags:
    - level-2
    - section-1
    - section-1.6
    - section-1.6.1
    - section-1.6.1.4
    - "1.6.1.4"
    - scored
