# Standards: 1.0.0
---

# 4.1.2 Ensure auditd service is enabled (Scored)
- name: 4.1.2 - Ensure auditd service is enabled
  yum:
    name: audit
  tags:
    - level-2
    - section-4
    - section-4.2
    - section-4.2.1
    - section-4.2.1.1
    - "4.2.1.1"
    - scored

- name: 4.1.2 - Ensure auditd service is enabled (Scored)
  systemd:
    name: "auditd"
    enabled: true
    state: started
  when: not in_container
  tags:
    - level-2
    - section-4
    - section-4.2
    - section-4.2.1
    - section-4.2.1.1
    - "4.2.1.1"
    - scored
