# Standards: 0.11
---

# 4.1.17 Ensure kernel module loading and unloading is collected (Scored)

- name: 4.1.17 Ensure kernel module loading and unloading is collected (Scored)
  shell: "grep modules {{ cis_audit_rules_filename }}"
  register: modules
  changed_when: False
  ignore_errors: true
  tags:
    - "4.1.17"
    - level-2 
    - section-4
    - scored
    - BP-1   


- name: 4.1.17 Ensure kernel module loading and unloading is collected(Verify registered output matches)
  lineinfile: 
    dest: "{{ cis_audit_rules_filename }}"
    line: "{{ item }}"
  with_items:
    - '# 4.1.17 Ensure kernel module loading and unloading is collected'
    - '-w /sbin/insmod -p x -k modules'
    - '-w /sbin/rmmod -p x -k modules'
    - '-w /sbin/modprobe -p x -k modules'
    - '-a always,exit arch=b64 -S init_module -S delete_module -k modules'
  when: 
    ("'-w /sbin/insmod -p x -k modules' not in modules.stdout") or
    ("'-w /sbin/rmmod -p x -k modules' not in modules.stdout") or
    ("'-w /sbin/modprobe -p x -k modules' not in modules.stdout") or 
    ("'-a always,exit arch=b64 -S init_module -S delete_module -k modules' not in modules.stdout") 
  tags:
    - "4.1.17"
    - level-2 
    - section-4
    - scored
    - BP-1






  
