# Standards: 1.0.0
---

# 4.1.4 Ensure events that modify date and time information are collected (Scored)

- name: 4.1.4 - Ensure events that modify date and time information are collected (Scored)
  command: "grep time-change {{ cis_audit_rules_filename }}"
  register: time-change
  changed_when: false
  ignore_errors: true
  tags:
    - level-2
    - section-4
    - section-4.1
    - section-4.1.4
    - "4.1.4"
    - scored

- name: 4.1.4 - Ensure events that modify date and time information are collected (Scored)(Verify registered output matches)
  lineinfile:
    dest: "{{ cis_audit_rules_filename }}"
    line: "{{ item }}"
  with_items:
    - '# 4.1.4 Ensure events that modify date and time information are collected'
    - '-a always,exit -F arch=b64 -S adjtimex -S settimeofday -k time-change'
    - '-a always,exit -F arch=b32 -S adjtimex -S settimeofday -S stime -k time-change'
    - '-a always,exit -F arch=b64 -S clock_settime -k time-change'
    - '-a always,exit -F arch=b32 -S clock_settime -k time-change'
    - '-w /etc/localtime -p wa -k time-change'
  when: >
    ("'-a always,exit -F arch=b64 -S adjtimex -S settimeofday -k time-change' not in time-change.stdout") or
    ("'-a always,exit -F arch=b32 -S adjtimex -S settimeofday -S stime -k time-change' not in time-change.stdout") or
    ("'-a always,exit -F arch=b64 -S clock_settime -k time-change' not in time-change.stdout") or
    ("'-a always,exit -F arch=b32 -S clock_settime -k time-change' not in time-change.stdout") or
    ("'-w /etc/localtime -p wa -k time-change' not in time-change.stdout")
  tags:
    - level-2
    - section-4
    - section-4.1
    - section-4.1.4
    - "4.1.4"
    - scored
