# Standards: 0.11
---

# 5.4.5 Ensure default user shell timeout is 900 seconds or less

- name: 5.4.5 - Ensure default user shell timeout is 900 seconds or less
  lineinfile:
    regexp: "^TMOUT"
    line: "TMOUT={{ cis_user_shell_timeout }}"
    dest: "{{ item }}"
  with_items: "{{ cis_umask_shell_files }}"
  tags:
    - level-2
    - section-5
    - "5.4.5"
    - scored
