# Standards: 1.0.0
---

# 5.4.5 Ensure default user shell timeout is 900 seconds or less 

- name: "SCORED | 5.4.5 | PATCH | Ensure default user shell timeout is 900 seconds or less"
  lineinfile:
      state: present
      dest: /etc/bashrc
      regexp: '^TMOUT'
      line: 'TMOUT=600'
  notify: Restart sshd
  tags:
    - level-2
    - section-5
    - "5.4.5"
    - scored
