# Standards: 0.11
---

# 6.1.1 Audit system file permissions

- name: 6.1.1 - Audit system file permissions
  shell: "rpm -Va --nomtime --nosize --nomd5 --nolinkto | egrep -v {{ cis_fs_permissions_exclusions | join(' | egrep -v ') }}"
  register: audit_6_1_1
  failed_when: audit_6_1_1.rc not in [0,1]
  tags:
    - level-2
    - section-6
    - "6.1.1"
    - scored

- name: 6.1.1 - Audit system file permissions
  fail:
    msg: "{{ audit_6_1_1.stdout }}"
  when:
    - audit_6_1_1.stdout_lines is defined and audit_6_1_1.stdout_lines|length > 0
    - fail_on_manual_remediation_actions
  tags:
    - level-2
    - section-6
    - "6.1.1"
    - scored

- name: 6.1.1 - Audit system file permissions
  debug:
    msg: "*** ACTION REQUIRED *** {{ audit_6_1_1.stdout }}"
  when:
    - audit_6_1_1.stdout_lines is defined and audit_6_1_1.stdout_lines|length > 0
    - not fail_on_manual_remediation_actions
  tags:
    - level-2
    - section-6
    - "6.1.1"
    - scored
