# Standards: 1.0.0
---

# 1.1.1.4 Ensure mounting of squashfs filesystems is disabled

- name: 1.1.1.4 - Check if CIS modprobe configuration file exists
  stat:
    path: "{{ cis_modprobe_conf_filename }}"
  register: modprobe
  tags:
    - level-1
    - section-1
    - section-1.1
    - section-1.1.1
    - section-1.1.1.4
    - "1.1.1.4"
    - scored

- name: 1.1.1.4 - Ensure mounting of squashfs filesystems is disabled
  copy:
    dest: "{{ cis_modprobe_conf_filename }}"
    content: "install squashfs /bin/true\n"
  when: modprobe.stat.exists is not defined or not modprobe.stat.exists
  tags:
    - level-1
    - section-1
    - section-1.1
    - section-1.1.1
    - section-1.1.1.4
    - "1.1.1.4"
    - scored

- name: 1.1.1.4 - Ensure mounting of squashfs filesystems is disabled
  lineinfile:
    dest: "{{ cis_modprobe_conf_filename }}"
    regexp: "^install squashfs"
    line: "install squashfs /bin/true"
  when: modprobe.stat.exists is defined and modprobe.stat.exists
  tags:
    - level-1
    - section-1
    - section-1.1
    - section-1.1.1
    - section-1.1.1.4
    - "1.1.1.4"
    - scored
