# Standards: 0.11
---

# 1.1.2 Ensure separate partition exists for /tmp (Scored)

- name: 1.1.2 - Ensure separate partition exists for /tmp (Scored)
  mount:
    name: "{{ item.mountpoint }}"
    state: present
    fstype: "{{item.fstype}}"
    src: "{{item.device}}"
    opts: "{{item.opts}}"
  with_items:
    - "{{ fs_mounts | selectattr('mountpoint', 'equalto', '/tmp') | list }}"
  tags:
      - level-1
      - section-1
      - "1.1.2"
      - scored

- name: 1.1.2 - Ensure the tmp.mount service is enabled for boot time auto-start
  systemd:
    name: tmp.mount
    enabled: yes
    masked: no
  tags:
      - level-1
      - section-1
      - "1.1.2"
      - scored
