# Standards: 0.11
---

# 1.1.9 Ensure nosuid option set on /var/tmp partition

- name: 1.1.9 - Ensure nosuid option set on /var/tmp partition
  mount:
    name: "{{ item.mountpoint }}"
    state: mounted
    fstype: "{{ item.fstype }}"
    src: "{{ item.device }}"
    opts: "{{ item.opts.split(',') | union(['nosuid']) | join(',') }}"
  when: item.mountpoint == '/var/tmp'
  with_items: "{{ fs_mounts }}"
  tags:
    - level-1
    - section-1
    - "1.1.9"
    - scored
