# Standards: 1.0.0
---

# 1.1.19 Disable Automounting

- name: 1.1.19 - Disable autofs
  systemd:
    name: autofs
    enabled: false
    state: stopped
  register: systemd
  failed_when: systemd is failed and not 'Could not find the requested service' in systemd.msg
  when: not in_container
  tags:
    - level-1
    - section-1
    - section-1.1
    - section-1.1.19
    - "1.1.19"
    - scored
