# Standards: 0.11
---

# 1.1.3 Ensure nodev option set on /tmp partition

- name: 1.1.3 - Ensure nodev option set on /tmp partition
  mount:
    name: "{{ item.mountpoint }}"
    state: mounted
    fstype: "{{ item.fstype }}"
    src: "{{ item.device }}"
    opts: "{{ item.opts.split(',') | union(['nodev']) | join(',') }}"
  with_items: 
    - "{{ fs_mounts | selectattr('mountpoint', 'equalto', '/tmp') | list }}"
  tags:
    - level-1
    - section-1
    - "1.1.3"
    - scored
