# Standards: 1.0.0
---

# 1.4.1 Ensure permissions on bootloader config are configured

- name: 1.4.1 - Check if grub bootloader file exists
  stat:
    path: "{{ cis_grub_bootloader_filename }}"
  register: grub
  tags:
    - level-1
    - section-1
    - section-1.4
    - section-1.4.1
    - "1.4.1"
    - scored

- name: 1.4.1 - Set permissions on grub configuration
  file:
    path: "{{ cis_grub_bootloader_filename }}"
    owner: root
    group: root
    mode: "og-rwx"
    state: file
  when: grub.stat.exists
  tags:
    - level-1
    - section-1
    - section-1.4
    - section-1.4.1
    - "1.4.1"
    - scored
