# Standards: 1.0.0
---

# 1.5.2 Ensure address space layout randomization (ASLR) is enabled (Scored)

- name: 1.5.2 - Ensure address space layout randomization is enabled
  sysctl:
    name: kernel.randomize_va_space
    value: 2
  when: not in_container
  tags:
    - level-1
    - section-1
    - section-1.5
    - section-1.5.2
    - "1.5.2"
    - scored
