# Standards: 0.11
---

# 1.6.1.5 Ensure SETroubleshoot is not installed (Scored)

- name: 1.6.1.5 Ensure SETroubleshoot is not installed (Scored)
  yum:
    name: mcstrans
    state: removed
  tags:
      - level-1
      - section-1
      - "1.6.1.5"
      - scored
