# Standards: 1.0.0
---

# 1.8 Ensure updates, patches, and additional security software are installed

- name: 1.8 - Ensure updates, patches, and additional security software are installed
  yum:
    name: "*"
    state: latest
  when:
    - full_upgrade
  tags:
    - level-1
    - section-1
    - section-1.8
    - "1.8"
    - not-scored
    - lint  # ANSIBLE0010
