# Standards: 1.0.0
---

# 2.1.1.2 Ensure ntp is configured
- name: Ensure ntp is configured
  block:
    - name: Set Options -u ntp:ntp in /etc/sysconfig/ntpd
      replace:
        path: /etc/sysconfig/ntpd
        regexp: '^OPTIONS=.*$'
        replace: 'OPTIONS="-u ntp:ntp"'

    - name: Set Restrict -6
      lineinfile:
        path: /etc/ntp.conf
        insertbefore: 'restrict default nomodify notrap nopeer noquery'
        line: 'restrict -6 default kod nomodify notrap nopeer noquery'

    - name: Set Restrict -4
      lineinfile:
        path: /etc/ntp.conf
        insertbefore: 'restrict -6 default kod nomodify notrap nopeer noquery'
        line: 'restrict -4 default kod nomodify notrap nopeer noquery'

    - name: Remove previous NTP servers
      lineinfile:
        path: /etc/ntp.conf
        regexp: '^server '
        state: absent
      when: cis_ntp_servers

    - name: Set NTP servers
      lineinfile:
        path: /etc/ntp.conf
        line: 'server {{ item }}'
        insertafter: '# Use and prefer the Amazon Time Service server'
      loop: '{{ cis_ntp_servers | reverse | list }}'
      when: cis_ntp_servers

    - name: Remove previous NTP pools
      lineinfile:
        path: /etc/ntp.conf
        regexp: '^pool '
        state: absent
      when: cis_ntp_pools

    - name: Set NTP pools
      lineinfile:
        path: /etc/ntp.conf
        line: 'pool {{ item }}'
        insertafter: '# Please consider joining the pool'
      loop: '{{ cis_ntp_pools | reverse | list }}'
      when: cis_ntp_pools

  when: cis_enable_ntp and not cis_enable_chrony
  tags:
    - level-1
    - section-2
    - section-2.1
    - section-2.1.1
    - section-2.1.1.2
    - "2.1.1.2"
    - scored
