# Standards: 0.11
---

# 2.1.6 Ensure LDAP server is not enabled

- name: 2.1.6 - Ensure LDAP server is not enabled
  service:
    name: "slapd"
    enabled: false
    state: stopped
  ignore_errors: true
  tags:
    - level-1
    - "2.1.6"
    - scored
