# Standards: 0.11
---

# 2.1.13 Ensure HTTP Proxy Server is not enabled

- name: 2.1.13 - Ensure HTTP Proxy Server is not enabled
  service:
    name: "squid"
    enabled: false
    state: stopped
  ignore_errors: true
  tags:
    - level-1
    - "2.1.13"
    - scored
