# Standards: 0.11
---

# 2.1.1.3 Ensure chrony is configured

- name: 2.1.1.3 verify a remote chrony server is configured
  shell: "egrep --no-filename -Rc '^(server|pool)' /etc/chrony.conf /etc/chrony.d"
  ignore_errors: true
  register: lines_matched
  when: cis_enable_chrony and not cis_enable_ntp
  tags:
    - level-1
    - "2.1.1.3"
    - scored

- set_fact:
    matchCount: "{{ lines_matched.stdout_lines|map('int')|sum }}"

- fail:
    msg: No server or pool seems to be configured for Chrony. Please fix this as per item 2.1.1.3 of the benchmark, and re-run this play.
  when: matchCount == 0
