# Standards: 0.11
---

# 2.1.20 Ensure rsync server is not enabled

- name: 2.1.20 - Ensure rsync server is not enabled
  service:
    name: "rsyncd"
    enabled: false
    state: stopped
  ignore_errors: true
  tags:
    - level-1
    - section-2
    - "2.1.20"
    - scored
