# Standards: 1.0.0
---

# 2.1.3 Ensure Avahi Server is not enabled

- name: 2.1.3 - Ensure Avahi Server is not enabled
  systemd:
    name: "avahi-daemon"
    enabled: false
    state: stopped
  register: systemd
  failed_when: systemd is failed and not 'Could not find the requested service' in systemd.msg
  when: not in_container
  tags:
    - level-1
    - section-2
    - section-2.1
    - section-2.1.3
    - "2.1.3"
    - scored
