# Standards: 0.11
---

# 2.1.16 Ensure NIS Server is not enabled

- name: 2.1.16 - Ensure NIS Server is not enabled
  service:
    name: "ypserv"
    enabled: false
    state: stopped
  ignore_errors: true
  tags:
    - level-1
    - "2.1.16"
    - scored
