# Standards: 0.11
---

# 2.1.11 Ensure IMAP and POP3 server is not enabled

- name: 2.1.11 - Ensure IMAP and POP3 server is not enabled
  service:
    name: "{{ item }}"
    enabled: false
    state: stopped
  with_items:
    - dovecot
    - cyrus-imapd
  ignore_errors: true
  tags:
    - level-1
    - "2.1.11"
    - scored
