# Standards: 0.11
---

# 2.1.1.3 Ensure chrony is configured

- name: 2.1.1.3 verify a remote chrony server is configured
  command: >
    egrep -c '^(server|pool)' /etc/chrony.conf
  register: line_matched
  when: cis_enable_chrony and not cis_enable_ntp
  tags:
    - level-1
    - "2.1.1.3"
    - scored

- fail:
    msg: No server or pool seems to be configured for Chrony. Please fix this as per item 2.1.1.3 of the benchmark, and re-run this play.
  when: line_matched == "0"
