# Standards: 1.0.0
---

# 2.1.1.3 Ensure chrony is configured
- name: Ensure chrony is configured
  block:
    - name: Set Options -u chrony in /etc/sysconfig/chrony"
      replace:
        path: /etc/sysconfig/chrony"
        regexp: '^OPTIONS=.*$'
        replace: 'OPTIONS="-u chrony""'

    - name: Remove previous NTP servers
      lineinfile:
        path: /etc/chrony.conf
        regexp: '^server '
        state: absent
      when: cis_ntp_servers

    - name: Set NTP servers
      lineinfile:
        path: /etc/chrony.conf
        line: 'server {{ item }}'
        insertafter: '# use the local instance NTP service, if available'
      loop: '{{ cis_ntp_servers | reverse | list }}'
      when: cis_ntp_servers

    - name: Remove previous NTP pools
      lineinfile:
        path: /etc/chrony.conf
        regexp: '^pool '
        state: absent
      when: cis_ntp_pools

    - name: Set NTP pools
      lineinfile:
        path: /etc/chrony.conf
        line: 'pool {{ item }}'
        insertafter: '# Please consider joining the pool'
      loop: '{{ cis_ntp_pools | reverse | list }}'
      when: cis_ntp_pools

  when: cis_enable_chrony and not cis_enable_ntp
  tags:
    - level-1
    - section-2
    - section-2.1
    - section-2.1.1
    - section-2.1.1.3
    - "2.1.1.3"
    - scored
