# Standards: 0.11
---

# 2.1.3 Ensure Avahi Server is not enabled

- name: 2.1.3 - Ensure Avahi Server is not enabled
  service:
    name: "avahi-daemon"
    enabled: false
    state: stopped
  ignore_errors: true
  tags:
    - level-1
    - "2.1.3"
    - scored
