# Standards: 0.11
---

# 2.2.3 Ensure talk client is not installed

- name: 2.2.3 - Ensure talk client is not installed
  yum:
    name: "talk"
    state: absent
  tags:
    - level-1
    - "2.2.3"
    - scored
