# Standards: 1.0.0
---

# 2.2.4 Ensure telnet client is not installed

- name: 2.2.4 - Ensure telnet client is not installed
  yum:
    name: "telnet"
    state: absent
  tags:
    - level-1
    - section-2
    - section-2.2
    - section-2.2.4
    - "2.2.4"
    - scored
