# Standards: 1.0.0
---

# 3.2.1 Ensure source routed packets are not accepted

- name: 3.2.1 - Ensure source routed packets are not accepted
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
  with_dict:
    "net.ipv4.conf.all.accept_source_route": 0
    "net.ipv4.conf.default.accept_source_route": 0
    "net.ipv6.conf.all.accept_source_route": 0
    "net.ipv6.conf.default.accept_source_route": 0
    "net.ipv4.route.flush": 1
    "net.ipv6.route.flush": 1
  when: not in_container
  tags:
    - level-1
    - section-3
    - section-3.2
    - section-3.2.1
    - "3.2.1"
    - scored
