# Standards: 1.0.0
---

# 3.3.4 Ensure permissions on /etc/hosts.allow are configured

- name: 3.3.4 - Ensure permissions on /etc/hosts.allow are configured
  file:
    path: "/etc/hosts.allow"
    owner: root
    group: root
    mode: 0644
  tags:
    - level-1
    - section-3
    - section-3.3
    - section-3.3.4
    - "3.3.4"
    - scored
