# Standards: 0.11
---

# 3.3.5 Ensure permissions on /etc/hosts.deny are configured

- name: 3.3.5 - Ensure permissions on /etc/hosts.deny are configured
  file:
    path: "/etc/hosts.deny"
    owner: root
    group: root
    mode: 0644
  tags:
    - level-1
    - section-3
    - "3.3.5"
    - scored
