# Standards: 1.0.0
---

# 3.4.1 Ensure DCCP is disabled

- name: 3.4.1 - Check if CIS modprobe configuration file exists
  stat:
    path: "{{ cis_modprobe_conf_filename }}"
  register: modprobe
  tags:
    - level-1
    - section-3
    - section-3.4
    - section-3.4.1
    - "3.4.1"
    - not-scored

- name: 3.4.1 - Ensure DCCP is disabled
  copy:
    dest: "{{ cis_modprobe_conf_filename }}"
    content: "install dccp /bin/true\n"
  when: modprobe.stat.exists is not defined or not modprobe.stat.exists
  tags:
    - level-1
    - section-3
    - section-3.4
    - section-3.4.1
    - "3.4.1"
    - not-scored

- name: 3.4.1 - Ensure DCCP is disabled
  lineinfile:
    dest: "{{ cis_modprobe_conf_filename }}"
    regexp: "^install dccp\\s+"
    line: "install dccp /bin/true"
  when: modprobe.stat.exists is defined and modprobe.stat.exists
  tags:
    - level-1
    - section-3
    - section-3.4
    - section-3.4.1
    - "3.4.1"
    - not-scored
