# Standards: 0.11
---

# 3.4.1 - Ensure DCCP is disabled

- name: 3.4.1 - Check if CIS modprobe configuration file exists
  stat:
    path: "{{ cis_modprobe_conf_filename }}"
  register: modprobe_3_5_1
  tags:
    - level-1
    - section-3
    - "3.4.1"
    - not-scored

- name: 3.4.1 - Ensure DCCP is disabled
  copy:
    dest: "{{ cis_modprobe_conf_filename }}"
    content: "install dccp /bin/true\n"
  when: modprobe_3_5_1.stat.exists is not defined or not modprobe_3_5_1.stat.exists
  tags:
    - level-1
    - section-3
    - "3.4.1"
    - not-scored

- name: 3.4.1 - Ensure DCCP is disabled
  lineinfile:
    dest: "{{ cis_modprobe_conf_filename }}"
    regexp: "^install dccp\\s+"
    line: "install dccp /bin/true"
  when: modprobe_3_5_1.stat.exists is defined and modprobe_3_5_1.stat.exists
  tags:
    - level-1
    - section-3
    - "3.4.1"
    - not-scored
