# Standards: 1.0.0
---

# 3.5.1.3 Ensure outbound and established connections are configured

- name: 3.5.1.3 - Ensure outbound and established connections are configured
  iptables:
    chain: "{{ item.chain }}"
    protocol: "{{ item.protocol }}"
    match: state
    ctstate: "{{ item.ctstate }}"
    jump: ACCEPT
  with_items:
    - chain: OUTPUT
      protocol: tcp
      ctstate: ESTABLISHED,NEW
    - chain: OUTPUT
      protocol: udp
      ctstate: ESTABLISHED,NEW
    - chain: OUTPUT
      protocol: icmp
      ctstate: ESTABLISHED,NEW
    - chain: INPUT
      protocol: tcp
      ctstate: ESTABLISHED
    - chain: INPUT
      protocol: udp
      ctstate: ESTABLISHED
    - chain: INPUT
      protocol: icmp
      ctstate: ESTABLISHED
  when: not in_container
  tags:
    - level-1
    - section-3
    - section-3.5
    - section-3.5.1
    - section-3.5.1.3
    - "3.5.1.3"
    - not-scored
