# Standards: 1.0.0
---

# 3.5.1.1 Ensure default deny firewall policy

- name: 3.5.1.1 - Ensure default deny firewall policy
  iptables:
    chain: "{{item}}"
    policy: DROP
  with_items:
    - INPUT
    - FORWARD
    - OUTPUT
  when: not in_container
  tags:
    - level-1
    - section-3
    - section-3.5
    - section-3.5.1
    - section-3.5.1.1
    - "3.5.1.1"
    - scored
