# Standards: 1.0.0
---

# 4.2.1.3 Ensure rsyslog default file permissions configured

- name: 4.2.1.3 - Ensure rsyslog default file permissions configured
  lineinfile:
    regexp: "^\\$FileCreateMode\\s+"
    line: "$FileCreateMode 0640"
    insertbefore: BOF
    dest: "/etc/rsyslog.conf"
  when: cis_enable_rsyslog
  notify:
    - Restart rsyslog
  tags:
    - level-1
    - section-4
    - section-4.2
    - section-4.2.1
    - section-4.2.1.3
    - "4.2.1.3"
    - scored
