# Standards: 1.0.0
---

# 4.2.1.1 Ensure rsyslog Service is enabled

- name: 4.2.1.1 - Ensure rsyslog is installed
  yum:
    name: rsyslog
  when: cis_enable_rsyslog and not cis_enable_syslog_ng
  tags:
    - level-1
    - section-4
    - section-4.2
    - section-4.2.1
    - section-4.2.1.1
    - "4.2.1.1"
    - scored

- name: 4.2.1.1 - Ensure rsyslog service is enabled
  systemd:
    name: rsyslog
    enabled: true
    state: started
  when:
    - not in_container
    - cis_enable_rsyslog
    - not cis_enable_syslog_ng
  tags:
    - level-1
    - section-4
    - section-4.2
    - section-4.2.1
    - section-4.2.1.1
    - "4.2.1.1"
    - scored
