# Standards: 1.0.0
---

# 5.1.1 Ensure cron daemon is enabled

- name: 5.1.1 - Ensure cron is installed
  yum:
    name: cronie
  tags:
    - level-1
    - section-5
    - section-5.1
    - section-5.1.1
    - "5.1.1"
    - scored

- name: 5.1.1 - Ensure cron daemon is enabled
  systemd:
    name: "crond"
    enabled: true
    state: started
  when: not in_container
  tags:
    - level-1
    - section-5
    - section-5.1
    - section-5.1.1
    - "5.1.1"
    - scored
