# Standards: 0.11
---

# 5.2.4 - Ensure SSH Protocol is set to 2

- name: 5.2.4 - Ensure SSH Protocol is set to 2
  lineinfile:
    regexp: "^Protocol\\s+"
    line: "Protocol 2"
    dest: "{{ cis_sshd_config_filename }}"
  notify: "Restart sshd"
  tags:
    - level-1
    - section-5
    - "5.2.4"
    - scored
