# Standards: 0.11
---

# 5.2.14 - Ensure only approved MAC algorithms are used

- name: 5.2.14 - Ensure only strong MAC algorithms are used
  lineinfile:
    regexp: "^MACs\\s+"
    line: "MACs {{ cis_sshd_macs }}"
    dest: "{{ cis_sshd_config_filename }}"
  notify: "Restart sshd"
  tags:
    - level-1
    - section-5
    - "5.2.14"
    - scored
