# Standards: 0.11
---

# 5.2.5 - Ensure SSH LogLevel is appropriate

- name: 5.2.5 - Ensure SSH LogLevel is set to INFO
  lineinfile:
    regexp: "^LogLevel\\s+"
    line: "LogLevel INFO"
    dest: "{{ cis_sshd_config_filename }}"
  notify: "Restart sshd"
  tags:
    - level-1
    - section-5
    - "5.2.5"
    - scored
