# Standards: 0.11
---

# 5.2.6 - Ensure SSH X11 forwarding is disabled

- name: 5.2.6 - Ensure SSH X11 forwarding is disabled
  lineinfile:
    regexp: "^X11Forwarding\\s+"
    line: "X11Forwarding no"
    dest: "{{ cis_sshd_config_filename }}"
  notify: "Restart sshd"
  tags:
    - level-1
    - section-5
    - "5.2.6"
    - scored
