# Standards: 0.11
---

# 5.2.8 Ensure SSH IgnoreRhosts is enabled

- name: 5.2.8 - Ensure SSH IgnoreRhosts is enabled
  lineinfile:
    regexp: "^IgnoreRhosts\\s+"
    line: "IgnoreRhosts yes"
    dest: "{{ cis_sshd_config_filename }}"
  notify: "Restart sshd"
  tags:
    - level-1
    - section-5
    - "5.2.8"
    - scored
