# Standards: 1.0.0
---

# 5.2.13 Ensure only strong ciphers are used (Scored)

- include: stat_sshd_config.yml
  tags:
    - level-1
    - section-5
    - section-5.2
    - section-5.2.13
    - "5.2.13"
    - scored

- name: 5.2.13 - Ensure only approved ciphers are used
  lineinfile:
    regexp: "^Ciphers\\s+"
    line: "Ciphers {{ cis_sshd_ciphers }}"
    dest: "/etc/ssh/sshd_config"
  when: sshd_config.stat.exists
  notify:
    - Restart sshd
  tags:
    - level-1
    - section-5
    - section-5.2
    - section-5.2.13
    - "5.2.13"
    - scored
