# Standards: 1.0.0
---

# 5.2.15 Ensure that strong Key Exchange algorithms are used (Scored)

- name: 5.2.15 - Ensure that strong Key Exchange algorithms are used
  debug:
    msg: "WARNING - This check has not been implemented yet."
  tags:
    - level-1
    - section-5
    - section-5.2
    - section-5.2.15
    - "5.2.15"
    - scored
    - todo
