# Standards: 1.0.0
---

# 5.2.9 Ensure SSH HostbasedAuthentication is disabled

- include: stat_sshd_config.yml
  tags:
    - level-1
    - section-5
    - section-5.2
    - section-5.2.9
    - "5.2.9"
    - scored

- name: 5.2.9 - Ensure SSH HostbasedAuthentication is disabled
  lineinfile:
    regexp: "^HostbasedAuthentication\\s+"
    line: "HostbasedAuthentication no"
    dest: "/etc/ssh/sshd_config"
  when: sshd_config.stat.exists
  notify:
    - Restart sshd
  tags:
    - level-1
    - section-5
    - section-5.2
    - section-5.2.9
    - "5.2.9"
    - scored
