# Standards: 1.0.0
---

# 5.2.5 Ensure SSH LogLevel is appropriate

- include: stat_sshd_config.yml
  tags:
    - level-1
    - section-5
    - section-5.2
    - section-5.2.5
    - "5.2.5"
    - scored

- name: 5.2.5 - Ensure SSH LogLevel is appropriate
  lineinfile:
    regexp: "^LogLevel\\s+"
    line: "LogLevel INFO"
    dest: "/etc/ssh/sshd_config"
  when: sshd_config.stat.exists
  notify:
    - Restart sshd
  tags:
    - level-1
    - section-5
    - section-5.2
    - section-5.2.5
    - "5.2.5"
    - scored
