# Standards: 1.0.0
---

# 5.2.3 Ensure permissions on SSH public host key files are configured (Scored)

- name: 5.2.3 - Ensure permissions on SSH public host key files are configured
  debug:
    msg: "WARNING - This check has not been implemented yet."
  tags:
    - level-1
    - section-5
    - section-5.2
    - section-5.2.3
    - "5.2.3"
    - scored
    - todo
