# Standards: 1.0.0
---

# 5.2.18 Ensure SSH access is limited
### Changed from something to 

- name: 5.2.18 - Configure SSH AllowUsers
  lineinfile:
    regexp: "^#?AllowUsers\\s+"
    line: "AllowUsers {{ cis_sshd_allow_users }}"
    dest: "/etc/ssh/sshd_config"
  when:
    - cis_sshd_allow_users is defined and cis_sshd_allow_users|trim != ""
  notify: Restart sshd
  tags:
    - level-1
    - section-5
    - section-5.2
    - section-5.2.18
    - "5.2.18"
    - scored

- name: 5.2.18 - Configure SSH AllowGroups
  lineinfile:
    regexp: "^#?AllowGroups\\s+"
    line: "AllowGroups {{ cis_sshd_allow_groups }}"
    dest: "/etc/ssh/sshd_config"
  when:
    - cis_sshd_allow_groups is defined and cis_sshd_allow_groups|trim != ""
  notify: Restart sshd
  tags:
    - level-1
    - section-5
    - section-5.2
    - section-5.2.18
    - "5.2.18"
    - scored

- name: 5.2.18 - Configure SSH DenyUsers
  lineinfile:
    regexp: "^#?DenyUsers\\s+"
    line: "DenyUsers {{ cis_sshd_deny_users }}"
    dest: "/etc/ssh/sshd_config"
  when:
    - cis_sshd_deny_users is defined and cis_sshd_deny_users|trim != ""
  notify: Restart sshd
  tags:
    - level-1
    - section-5
    - section-5.2
    - section-5.2.18
    - "5.2.18"
    - scored

- name: 5.2.18 - Configure SSH DenyGroups
  lineinfile:
    regexp: "^#?DenyGroups\\s+"
    line: "DenyGroups {{ cis_sshd_deny_groups }}"
    dest: "/etc/ssh/sshd_config"
  when:
    - cis_sshd_deny_groups is defined and cis_sshd_deny_groups|trim != ""
  notify: Restart sshd
  tags:
    - level-1
    - section-5
    - section-5.2
    - section-5.2.18
    - "5.2.18"
    - scored
