# Standards: 1.0.0
---

# 5.2.16 Ensure SSH Idle Timeout Interval is configured

- include: stat_sshd_config.yml
  tags:
    - level-1
    - section-5
    - section-5.2
    - section-5.2.16
    - "5.2.16"
    - scored

- name: 5.2.16 - Ensure SSH Client Alive Interval is configured
  lineinfile:
    regexp: "^ClientAliveInterval\\s+"
    line: "ClientAliveInterval {{ cis_sshd_client_alive_interval }}"
    dest: "/etc/ssh/sshd_config"
  when: sshd_config.stat.exists
  notify:
    - Restart sshd
  tags:
    - level-1
    - section-5
    - section-5.2
    - section-5.2.16
    - "5.2.16"
    - scored

- name: 5.2.16 - Ensure SSH Client Alive Count Max is configured
  lineinfile:
    regexp: "^ClientAliveCountMax\\s+"
    line: "ClientAliveCountMax {{ cis_sshd_client_alive_count_max }}"
    dest: "/etc/ssh/sshd_config"
  when: sshd_config.stat.exists
  notify:
    - Restart sshd
  tags:
    - level-1
    - section-5
    - section-5.2
    - section-5.2.16
    - "5.2.16"
    - scored
