# Standards: 1.0.0
---

# 5.3.4 Ensure password hashing algorithm is SHA-512

- name: 5.3.4 - Ensure authconfig is installed
  yum:
    name: authconfig
  tags:
    - level-1
    - section-5
    - section-5.3
    - section-5.3.4
    - "5.3.4"
    - scored

- name: 5.3.4 - Ensure password hashing algorithm is SHA-512
  command: "authconfig --update --passalgo=sha512"
  tags:
    - level-1
    - section-5
    - section-5.3
    - section-5.3.4
    - "5.3.4"
    - scored
    - non-idempotent
    - lint  # ANSIBLE0012
