# Standards: 1.0.0
---

# 5.4.1.2 Ensure minimum days between password changes is 7 or more

- name: 5.4.1.2 - Obtain a list of user accounts
  shell: "egrep ^[^:]+:[^\\!*] /etc/shadow | cut -d: -f1"
  register: egrep
  check_mode: false
  changed_when: false
  tags:
    - level-1
    - section-5
    - section-5.4
    - section-5.4.1
    - section-5.4.1.2
    - "5.4.1.2"
    - scored

- name: 5.4.1.2 - Ensure minimum days between password changes is 7 or more
  lineinfile:
    dest: "/etc/login.defs"
    regexp: "^PASS_MIN_DAYS\\s+"
    line: "PASS_MIN_DAYS {{ cis_pass_min_days }}"
  tags:
    - level-1
    - section-5
    - section-5.4
    - section-5.4.1
    - section-5.4.1.2
    - "5.4.1.2"
    - scored

- name: 5.4.1.2 - Set minimum password change interval for all user accounts
  command: "chage --mindays {{ cis_pass_min_days }} {{ item }}"
  with_items: "{{ egrep.stdout_lines }}"
  tags:
    - level-1
    - section-5
    - section-5.4
    - section-5.4.1
    - section-5.4.1.2
    - "5.4.1.2"
    - scored
    - lint  # ANSIBLE0012
