# Standards: 1.0.0
---

# 5.4.1.3 Ensure password expiration warning days is 7 or more

- name: 5.4.1.3 - Obtain a list of user accounts
  shell: "egrep ^[^:]+:[^\\!*] /etc/shadow | cut -d: -f1"
  register: egrep
  check_mode: false
  changed_when: false
  tags:
    - level-1
    - section-5
    - section-5.4
    - section-5.4.1
    - section-5.4.1.3
    - "5.4.1.3"
    - scored

- name: 5.4.1.3 - Ensure password expiration warning days is 7 or more
  lineinfile:
    dest: "/etc/login.defs"
    regexp: "^PASS_WARN_AGE\\s+"
    line: "PASS_WARN_AGE {{ cis_pass_warn_age }}"
  tags:
    - level-1
    - section-5
    - section-5.4
    - section-5.4.1
    - section-5.4.1.3
    - "5.4.1.3"
    - scored

- name: 5.4.1.3 - Set password expiration warning for all user accounts
  command: "chage --warndays {{ cis_pass_warn_age }} {{ item }}"
  with_items: "{{ egrep.stdout_lines }}"
  tags:
    - level-1
    - section-5
    - section-5.4
    - section-5.4.1
    - section-5.4.1.3
    - "5.4.1.3"
    - scored
    - lint  # ANSIBLE0012
