# Standards: 1.0.0
---

# 6.1.6 Ensure permissions on /etc/passwd- are configured

- name: 6.1.6 - Ensure permissions on /etc/passwd- are configured
  file:
    path: /etc/passwd-
    owner: root
    group: root
    mode: 0600
  tags:
    - level-1
    - section-6
    - section-6.1
    - section-6.1.6
    - "6.1.6"
    - scored
