# Standards: 1.0.0
---

# 6.1.7 Ensure permissions on /etc/shadow- are configured

- name: 6.1.7 - Ensure permissions on /etc/shadow- are configured
  file:
    path: /etc/shadow-
    owner: root
    group: root
    mode: 0000
  tags:
    - level-1
    - section-6
    - section-6.1
    - section-6.1.7
    - "6.1.7"
    - scored
