# Standards: 1.0.0
---

# 6.1.8 Ensure permissions on /etc/group- are configured

- name: 6.1.8 - Ensure permissions on /etc/group- are configured
  file:
    path: /etc/group-
    owner: root
    group: root
    mode: 0600
  tags:
    - level-1
    - section-6
    - section-6.1
    - section-6.1.8
    - "6.1.8"
    - scored
