# Standards: 1.0.0
---

# 6.1.13 Audit SUID executables

- name: 6.1.13 - Check if any SUID executables exist
  shell: "df --local -P | awk {'if (NR!=1) print $6'} | xargs -I '{}' find '{}' -xdev -type f -perm -4000"
  register: audit
  tags:
    - level-1
    - section-6
    - section-6.1
    - section-6.1.13
    - "6.1.13"
    - scored
    - non-idempotent
    - lint  # ANSIBLE0012

- name: 6.1.13 - Audit SUID executables
  fail:
    msg: "{{ audit.stdout_lines }}"
  when:
    - audit.stdout_lines is defined and audit.stdout_lines|length > 0
    - fail_on_manual_remediation_actions
  tags:
    - level-1
    - section-6
    - section-6.1
    - section-6.1.13
    - "6.1.13"
    - scored

- name: 6.1.13 - Audit SUID executables
  debug:
    msg: "*** ACTION REQUIRED *** {{ audit.stdout }}"
  when:
    - audit.stdout_lines is defined and audit.stdout_lines|length > 0
    - not fail_on_manual_remediation_actions
  tags:
    - level-1
    - section-6
    - section-6.1
    - section-6.1.13
    - "6.1.13"
    - scored
