# Standards: 1.0.0
---

# 6.2.2 Ensure no legacy "+" entries exist in /etc/passwd

- name: 6.2.2 - Ensure no legacy "+" entries exist in /etc/passwd
  replace:
    dest: "/etc/passwd"
    regexp: "^\\+:.*\n"
  tags:
    - level-1
    - section-6
    - section-6.2
    - section-6.2.2
    - "6.2.2"
    - scored
