# Standards: 1.0.0
---

# 6.2.4 Ensure no legacy "+" entries exist in /etc/group

- name: 6.2.4 - Ensure no legacy "+" entries exist in /etc/group
  replace:
    dest: "/etc/group"
    regexp: "^\\+:.*\n"
  tags:
    - level-1
    - section-6
    - section-6.2
    - section-6.2.4
    - "6.2.4"
    - scored
