# Standards: 1.0.0
---

# 6.2.3 Ensure no legacy "+" entries exist in /etc/shadow

- name: 6.2.3 - Ensure no legacy "+" entries exist in /etc/shadow
  replace:
    dest: "/etc/shadow"
    regexp: "^\\+:.*\n"
  tags:
    - level-1
    - section-6
    - section-6.2
    - section-6.2.3
    - "6.2.3"
    - scored
