# Standards: 1.0.0
---

# 6.2.7 Ensure all users' home directories exist

- name: 6.2.7 - Audit existence of users' home directories
  script: "{{ role_path }}/files/audit_6.2.7.sh"
  check_mode: false
  changed_when: false
  register: audit
  tags:
    - level-1
    - section-6
    - section-6.2
    - section-6.2.7
    - "6.2.7"
    - scored

- name: 6.2.7 - Ensure users' home directories exist.
  user:
    name: "{{ item.split(':')[0] }}"
    home: "{{ item.split(':')[1] }}"
  when: audit.stdout_lines is defined and audit.stdout_lines|length > 0
  with_items: "{{ audit.stdout_lines }}"
  tags:
    - level-1
    - section-6
    - section-6.2
    - section-6.2.7
    - "6.2.7"
    - scored
